### ISSUE TITLE
Add End Game Mechanics

### ISSUE THREAD

**Issue by somfieaw** [somfieaw/Tank-War-RL#5]
Add end game mechanics:
- [x] check bullet collision #13 
- [x] check tank collision #13 
- [x] check out-of-border #13 
- [x] detect winner/loser #13
